[[GAP_pkg_curlinterface]]
arch = "aarch64"
git-tree-sha1 = "880cba39afa155104b6fe68283d005c6f95053dc"
os = "macos"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "1f5346eded019fb7516092e3e93ab72e7defa923a44361d76caeedb2fcc2c7bc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v200.400.1+0/GAP_pkg_curlinterface.v200.400.1.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "aarch64"
git-tree-sha1 = "cc49361b8ce66178da83661ed625c879cb6b0ed9"
libc = "glibc"
os = "linux"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "3169b48ae61700bc9dff839db6abd039bde630b089ca40b14ca66fd68b3d24b6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v200.400.1+0/GAP_pkg_curlinterface.v200.400.1.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "aarch64"
git-tree-sha1 = "d5bb6c18c01b01d4adb504bc3d53d3aa9e4eb414"
libc = "musl"
os = "linux"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "aecac8502448f71c1b65eb8d638cddc43b75799aad88bad8043e860223ab73a2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v200.400.1+0/GAP_pkg_curlinterface.v200.400.1.aarch64-linux-musl.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "aarch64"
git-tree-sha1 = "84663ef69ec701379e0a7c8887a187a771fd4f86"
os = "freebsd"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "3e2fd9d7c421dfc21fc376ec68c44a1030f00877f229e3e9ac9a2d93c1970a73"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v200.400.1+0/GAP_pkg_curlinterface.v200.400.1.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "powerpc64le"
git-tree-sha1 = "fee361ed46ac5cf7fe38edb5b289fe0a0801ec57"
libc = "glibc"
os = "linux"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "6440b0c7c1d847a3f3a1f9834f00a2ed4055e6cd5e145ceb2a1fb313962f99d6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v200.400.1+0/GAP_pkg_curlinterface.v200.400.1.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "riscv64"
git-tree-sha1 = "1ae2d393fbb77eb391482d88e6ba114bc596e0e2"
libc = "glibc"
os = "linux"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "9ecad284e609b34234d3b609e01e17a8740c1f66dc49420f38e880b8dec68f71"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v200.400.1+0/GAP_pkg_curlinterface.v200.400.1.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "x86_64"
git-tree-sha1 = "f2c272fde2a5fbae4be5ba826d7b263ff4dd1cb2"
os = "macos"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "1bde37791ff21ba45c5852fd8a93f723a60cb96b45c710555b540e6caea25c3a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v200.400.1+0/GAP_pkg_curlinterface.v200.400.1.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "x86_64"
git-tree-sha1 = "c6f041b784163981f14dddb25de4d13eebeb8918"
libc = "glibc"
os = "linux"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "0f69886f5a13bdc9faa2fa9f8119479289841f52fd6e52975d4599d287cc1a5d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v200.400.1+0/GAP_pkg_curlinterface.v200.400.1.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "x86_64"
git-tree-sha1 = "d58daf72ed25ebb2618f33a2d535672dfb49fc31"
libc = "musl"
os = "linux"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "a821895de95a612ffeb71d6cd061d12d81963733b5fd0ef26f3494c40f53cddd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v200.400.1+0/GAP_pkg_curlinterface.v200.400.1.x86_64-linux-musl.tar.gz"
[[GAP_pkg_curlinterface]]
arch = "x86_64"
git-tree-sha1 = "260558941fefddbb3aae072375d546b87f661489"
os = "freebsd"

    [[GAP_pkg_curlinterface.download]]
    sha256 = "2231e4deae4b960455870fe20280e8bb30c3a213c565d4462298e5453b20fd8f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_curlinterface_jll.jl/releases/download/GAP_pkg_curlinterface-v200.400.1+0/GAP_pkg_curlinterface.v200.400.1.x86_64-unknown-freebsd.tar.gz"
